In [1]:
import pandas as pd 
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

In [2]:
df_Results = pd.read_csv('DataSets/Scores/LLM_Answer_Scores.csv')

In [3]:
df_Results

,Prompt_ID,Content_Type,Model,temperature,top_p,top_k,runtime,BLEU,Precision,Recall,F1 Score,NEUTRAL,ENTAILMENT,CONTRADICTION
0,1,NOC,QWEN 2.5,0.2,0.5,20,7.041744,0.460551,0.600000,0.367347,0.455696,0.926761,0.070157,0.003082
1,1,NOC,QWEN 2.5,0.2,0.5,40,1.287806,0.460551,0.610169,0.367347,0.458599,0.896464,0.100589,0.002947
2,1,NOC,QWEN 2.5,0.2,0.5,90,1.351361,0.460551,0.603175,0.387755,0.472050,0.910539,0.086862,0.002600
3,1,NOC,QWEN 2.5,0.2,0.7,20,1.286819,0.460551,0.600000,0.367347,0.455696,0.926761,0.070157,0.003082
4,1,NOC,QWEN 2.5,0.2,0.7,40,1.324588,0.460551,0.610169,0.367347,0.458599,0.885681,0.111349,0.002970
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3235,30,Graduate Survey,GRANITE 3.3,0.9,0.7,40,0.992716,0.116390,0.325000,0.351351,0.337662,0.996101,0.003460,0.000439
3236,30,Graduate Survey,GRANITE 3.3,0.9,0.7,90,0.987194,0.116390,0.325000,0.351351,0.337662,0.995997,0.003569,0.000434
3237,30,Graduate Survey,GRANITE 3.3,0.9,0.9,20,1.065169,0.592437,0.568182,0.675676,0.617284,0.996151,0.003396,0.000453
3238,30,Graduate Survey,GRANITE 3.3,0.9,0.9,40,1.067865,0.572815,0.666667,0.810811,0.731707,0.996525,0.002986,0.000489
3239,30,Graduate Survey,GRANITE 3.3,0.9,0.9,90,1.030967,0.116390,0.333333,0.351351,0.342105,0.996181,0.003365,0.000453

In [4]:
df_Results['Model'].unique()

array(['QWEN 2.5', 'LLAMA 3.1', 'GEMMA 2', 'GRANITE 3.3'], dtype=object)

In [85]:
Model_Discrete_Map = {
    'QWEN 2.5': "#175741",
    'LLAMA 3.1': "#8F4D21",
    'GEMMA 2': "#731812",
    'GRANITE 3.3': "#0F275C"
}

In [86]:
Stats_Box = px.box(
    title='BLEU, Precision, Recall and F1 Score Comparison Across AI Models',
    data_frame=df_Results,
    y=['BLEU','Precision','Recall','F1 Score'],
    color='Model',
    color_discrete_map=Model_Discrete_Map,
    width=1200,
    height=900,
    template='ggplot2'
)

Stats_Box.update_layout(
    title_font=dict(size=16),  # Set the title font size
    font=dict(size=12),  # Set general font size for labels and axis titles
            hoverlabel=dict(
                font_size=20  # Set font size for hover data
            ),

             legend=dict(
                orientation='h',       
                yanchor='bottom',     
                y=-0.3,               
                xanchor='center',      
                 x=0.5,                 
                font=dict(size=16)     
            ),
            plot_bgcolor="#CDD0D4", 
            xaxis=dict(
                title="Metric",
                title_font=dict(size=14),
                tickfont=dict(size=12),

            ),
            yaxis=dict(
                title="Value",
                title_font=dict(size=14),
                tickfont=dict(size=12),
    )
)

Stats_Box.show()

In [45]:
RunTime_Box = px.box(
    title='Run Time (in seconds) Comparison Across AI Models',
    data_frame=df_Results,
    y='runtime',
    color='Model',
    color_discrete_map=Model_Discrete_Map,
    width=1500,
    height=900,
    template='ggplot2',
    facet_col='Content_Type'
)

RunTime_Box.update_layout(
    title_font=dict(size=16),  # Set the title font size
    font=dict(size=12),  # Set general font size for labels and axis titles
            hoverlabel=dict(
                font_size=20  # Set font size for hover data
            ),

             legend=dict(
                orientation='h',       
                yanchor='bottom',     
                y=-0.3,               
                xanchor='center',      
                 x=0.5,                 
                font=dict(size=16)     
            ),
            plot_bgcolor="#CDD0D4", 
            xaxis=dict(
                title="Distributions",
                title_font=dict(size=14),
                tickfont=dict(size=12),

            ),
            yaxis=dict(
                title="Run Time (in seconds)",
                title_font=dict(size=14),
                tickfont=dict(size=12),
    )
)

RunTime_Box.for_each_xaxis(
    lambda ax: ax.update(title_text="Distributions")
)


RunTime_Box.show()

In [46]:
RunTime_Box.write_image("Figures/Run_Time_Based_On_Content.svg")

In [87]:
Stats_Box.write_image('Figures/Classification_Metrics_Comparison.svg')

In [17]:
NLI_Box = px.box(
    title='Logicial Consistency Comparison Across AI Models',
    data_frame=df_Results,
    y=['NEUTRAL','ENTAILMENT','CONTRADICTION'],
    color='Model',
    color_discrete_map=Model_Discrete_Map,
    width=1200,
    height=900,
    template='ggplot2'
)

NLI_Box.update_layout(
    title_font=dict(size=16),  # Set the title font size
    font=dict(size=12),  # Set general font size for labels and axis titles
            hoverlabel=dict(
                font_size=20  # Set font size for hover data
            ),

             legend=dict(
                orientation='h',       
                yanchor='bottom',     
                y=-0.3,               
                xanchor='center',      
                 x=0.5,                 
                font=dict(size=16)     
            ),
            plot_bgcolor="#CDD0D4", 
            xaxis=dict(
                title="Consistency Label",
                title_font=dict(size=14),
                tickfont=dict(size=12),

            ),
            yaxis=dict(
                title="Value",
                title_font=dict(size=14),
                tickfont=dict(size=12),
    )
)

NLI_Box.show()

In [18]:
NLI_Box.write_image("Figures/Logicical_Consistency_Comparisons.svg")

In [88]:
Stats_Box_Temperature = px.box(
    title='BLEU, Precision, Recall and F1 Score Comparison Across AI Models (Temperature Differences)',
    data_frame=df_Results,
    y=['BLEU','Precision','Recall','F1 Score'],
    color='Model',
    color_discrete_map=Model_Discrete_Map,
    width=1200,
    height=900,
    template='ggplot2',
    facet_col='temperature',
)

Stats_Box_Temperature.update_layout(
    title_font=dict(size=16),  # Set the title font size
    font=dict(size=12),  # Set general font size for labels and axis titles
            hoverlabel=dict(
                font_size=20  # Set font size for hover data
            ),

             legend=dict(
                orientation='h',       
                yanchor='bottom',     
                y=-0.3,               
                xanchor='center',      
                 x=0.5,                 
                font=dict(size=16)     
            ),
            plot_bgcolor="#CDD0D4", 
            xaxis=dict(
                title="Metric",
                title_font=dict(size=14),
                tickfont=dict(size=12),

            ),
            yaxis=dict(
                title="Value",
                title_font=dict(size=14),
                tickfont=dict(size=12),
    )
)

Stats_Box_Temperature.for_each_xaxis(
    lambda ax: ax.update(title_text="Metric")
)

Stats_Box_Temperature.show()

In [89]:
Stats_Box_Temperature.write_image("Figures/Classifcation_Metrics_Comparison_Temperature_Based.svg")

In [32]:
NLI_Box_Temperature = px.box(
    title='Logicial Consistency Comparison Across AI Models',
    data_frame=df_Results,
    y=['NEUTRAL','ENTAILMENT','CONTRADICTION'],
    color='Model',
    color_discrete_map=Model_Discrete_Map,
    width=1200,
    height=900,
    template='ggplot2',
    facet_col='temperature'
)

NLI_Box_Temperature.update_layout(
    title_font=dict(size=16),  # Set the title font size
    font=dict(size=12),  # Set general font size for labels and axis titles
            hoverlabel=dict(
                font_size=20  # Set font size for hover data
            ),

             legend=dict(
                orientation='h',       
                yanchor='bottom',     
                y=-0.3,               
                xanchor='center',      
                 x=0.5,                 
                font=dict(size=16)     
            ),
            plot_bgcolor="#CDD0D4", 
            xaxis=dict(
                title="Consistency Label",
                title_font=dict(size=14),
                tickfont=dict(size=12),

            ),
            yaxis=dict(
                title="Value",
                title_font=dict(size=14),
                tickfont=dict(size=12),
    )
)
NLI_Box_Temperature.for_each_xaxis(
    lambda ax: ax.update(title_text="Consistency Label")
)

NLI_Box_Temperature.show()

In [33]:
NLI_Box_Temperature.write_image('Figures/Logicical_Consistency_Comparisons_Temperature_Based.svg')

In [90]:
Stats_Box_Content = px.box(
    title='BLEU, Precision, Recall and F1 Score Comparison Across AI Models (Based on Content Type)',
    data_frame=df_Results,
    y=['BLEU','Precision','Recall','F1 Score'],
    color='Model',
    color_discrete_map=Model_Discrete_Map,
    width=1500,
    height=900,
    template='ggplot2',
    facet_col='Content_Type',
)

Stats_Box_Content.update_layout(
    title_font=dict(size=16),  # Set the title font size
    font=dict(size=12),  # Set general font size for labels and axis titles
            hoverlabel=dict(
                font_size=20  # Set font size for hover data
            ),

             legend=dict(
                orientation='h',       
                yanchor='bottom',     
                y=-0.3,               
                xanchor='center',      
                 x=0.5,                 
                font=dict(size=16)     
            ),
            plot_bgcolor="#CDD0D4", 
            xaxis=dict(
                title="Metric",
                title_font=dict(size=14),
                tickfont=dict(size=12),

            ),
            yaxis=dict(
                title="Value",
                title_font=dict(size=14),
                tickfont=dict(size=12),
    )
)

Stats_Box_Content.for_each_xaxis(
    lambda ax: ax.update(title_text="Metric")
)

Stats_Box_Content.show()

In [91]:
Stats_Box_Tops = px.box(
    title='BLEU ,Precision, Recall and F1 Score Comparison Across AI Models (Top P and Top K)',
    data_frame=df_Results,
    y=['BLEU','Precision','Recall','F1 Score'],
    color='Model',
    color_discrete_map=Model_Discrete_Map,
    width=1500,
    height=1000,
    template='ggplot2',
    facet_col='top_p',
    facet_row='top_k'
)

Stats_Box_Tops.update_layout(
    title_font=dict(size=16),  # Set the title font size
    font=dict(size=12),  # Set general font size for labels and axis titles
            hoverlabel=dict(
                font_size=20  # Set font size for hover data
            ),

             legend=dict(
                orientation='h',       
                yanchor='bottom',     
                y=-0.3,               
                xanchor='center',      
                 x=0.5,                 
                font=dict(size=16)     
            ),
            plot_bgcolor="#CDD0D4", 
            xaxis=dict(
                title="Metric",
                title_font=dict(size=14),
                tickfont=dict(size=12),

            ),
            yaxis=dict(
                title="Value",
                title_font=dict(size=14),
                tickfont=dict(size=12),
    )
)

# Stats_Box_Tops.for_each_xaxis(
#     lambda ax: ax.update(title_text="Metric")
# )

# Stats_Box_Tops.for_each_yaxis(
#     lambda ax: ax.update(title_text="Value")
# )

Stats_Box_Tops.show()

In [92]:
Stats_Box_Tops.write_image('Figures/Classification_Metrics_Top_p_and_k.svg')

In [59]:
df_Results["Consistency Label"] = (
    df_Results[["NEUTRAL", "ENTAILMENT", "CONTRADICTION"]]
    .idxmax(axis=1)
    .str.title()
)

df_Results

,Prompt_ID,Content_Type,Model,temperature,top_p,top_k,runtime,BLEU,Precision,Recall,F1 Score,NEUTRAL,ENTAILMENT,CONTRADICTION,Consistency Label
0,1,NOC,QWEN 2.5,0.2,0.5,20,7.041744,0.460551,0.600000,0.367347,0.455696,0.926761,0.070157,0.003082,Neutral
1,1,NOC,QWEN 2.5,0.2,0.5,40,1.287806,0.460551,0.610169,0.367347,0.458599,0.896464,0.100589,0.002947,Neutral
2,1,NOC,QWEN 2.5,0.2,0.5,90,1.351361,0.460551,0.603175,0.387755,0.472050,0.910539,0.086862,0.002600,Neutral
3,1,NOC,QWEN 2.5,0.2,0.7,20,1.286819,0.460551,0.600000,0.367347,0.455696,0.926761,0.070157,0.003082,Neutral
4,1,NOC,QWEN 2.5,0.2,0.7,40,1.324588,0.460551,0.610169,0.367347,0.458599,0.885681,0.111349,0.002970,Neutral
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3235,30,Graduate Survey,GRANITE 3.3,0.9,0.7,40,0.992716,0.116390,0.325000,0.351351,0.337662,0.996101,0.003460,0.000439,Neutral
3236,30,Graduate Survey,GRANITE 3.3,0.9,0.7,90,0.987194,0.116390,0.325000,0.351351,0.337662,0.995997,0.003569,0.000434,Neutral
3237,30,Graduate Survey,GRANITE 3.3,0.9,0.9,20,1.065169,0.592437,0.568182,0.675676,0.617284,0.996151,0.003396,0.000453,Neutral
3238,30,Graduate Survey,GRANITE 3.3,0.9,0.9,40,1.067865,0.572815,0.666667,0.810811,0.731707,0.996525,0.002986,0.000489,Neutral
3239,30,Graduate Survey,GRANITE 3.3,0.9,0.9,90,1.030967,0.116390,0.333333,0.351351,0.342105,0.996181,0.003365,0.000453,Neutral

In [60]:
df_Entailment_Instances = df_Results[df_Results['Consistency Label']=='Entailment']
df_Entailment_Instances

,Prompt_ID,Content_Type,Model,temperature,top_p,top_k,runtime,BLEU,Precision,Recall,F1 Score,NEUTRAL,ENTAILMENT,CONTRADICTION,Consistency Label
6,1,NOC,QWEN 2.5,0.2,0.9,20,1.421864,0.460551,0.565217,0.397959,0.467066,0.480265,0.517067,0.002667,Entailment
27,1,NOC,LLAMA 3.1,0.2,0.5,20,5.624260,0.491600,0.563380,0.408163,0.473373,0.371306,0.626751,0.001944,Entailment
31,1,NOC,LLAMA 3.1,0.2,0.7,40,0.901808,0.491600,0.608696,0.428571,0.502994,0.356812,0.641252,0.001936,Entailment
33,1,NOC,LLAMA 3.1,0.2,0.9,20,0.960793,0.491600,0.563380,0.408163,0.473373,0.371306,0.626751,0.001944,Entailment
35,1,NOC,LLAMA 3.1,0.2,0.9,90,0.927384,0.491600,0.577465,0.418367,0.485207,0.367627,0.630037,0.002335,Entailment
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3203,30,Graduate Survey,GEMMA 2,0.5,0.9,90,1.593448,0.278941,0.416667,0.675676,0.515464,0.028144,0.968015,0.003841,Entailment
3204,30,Graduate Survey,GEMMA 2,0.9,0.5,20,1.578775,0.226567,0.385965,0.594595,0.468085,0.028926,0.968393,0.002681,Entailment
3207,30,Graduate Survey,GEMMA 2,0.9,0.7,20,1.502533,0.278941,0.500000,0.783784,0.610526,0.287131,0.710355,0.002515,Entailment
3208,30,Graduate Survey,GEMMA 2,0.9,0.7,40,1.835460,0.226567,0.309859,0.594595,0.407407,0.035535,0.945701,0.018764,Entailment
3209,30,Graduate Survey,GEMMA 2,0.9,0.7,90,1.519829,0.315915,0.385965,0.594595,0.468085,0.034908,0.961713,0.003379,Entailment

In [64]:
df_Entailment_Distributions = df_Entailment_Instances.groupby(['Model'])['ENTAILMENT'].describe().round(3).reset_index()
df_Entailment_Distributions

         Model  count   mean    std    min    25%    50%    75%    max
0      GEMMA 2  537.0  0.833  0.152  0.441  0.722  0.904  0.962  0.989
1  GRANITE 3.3  465.0  0.881  0.121  0.381  0.824  0.926  0.985  0.993
2    LLAMA 3.1  532.0  0.877  0.137  0.421  0.802  0.942  0.983  0.993
3     QWEN 2.5  520.0  0.885  0.127  0.351  0.798  0.942  0.978  0.993

In [68]:
Entailment_Scatter = px.bar(
    title='Number of Entailments vs. Avg Confidence in Label',
    data_frame=df_Entailment_Distributions,
    x='Model',
    y='count',
    color='Model',
    color_discrete_map=Model_Discrete_Map,
    width=1500,
    height=1000,
    template='ggplot2',
    text='count'
)

Entailment_Scatter.add_trace(
    go.Scatter(
        x=df_Entailment_Distributions['Model'],
        y=df_Entailment_Distributions['mean'],
        mode='lines+markers',
        marker=dict(color='#474545', size=18),
        line=dict(color="#1A1919", width=2.5),
        name='Avg Confidence in Label',
        yaxis='y2'   # <-- Secondary axis
    )
)

Entailment_Scatter.update_layout(
    title_font=dict(size=16),
    font=dict(size=12),

    hoverlabel=dict(font_size=20),

    legend=dict(
        orientation='h',
        yanchor='bottom',
        y=-0.3,
        xanchor='center',
        x=0.5,
        font=dict(size=16)
    ),

    plot_bgcolor="#CDD0D4",

    xaxis=dict(
        title="Model",
        title_font=dict(size=14),
        tickfont=dict(size=12)
    ),

    yaxis=dict(
        title="Entailment Count",
        title_font=dict(size=14),
        tickfont=dict(size=12)
    ),

    yaxis2=dict(
        title="Avg Confidence",
        title_font=dict(size=14),
        tickfont=dict(size=12),
        overlaying='y',   # share same x-axis
        side='right'
    )
)

Entailment_Scatter.show()

In [69]:
Entailment_Scatter.write_image("Figures/Entailment_Count_vs_Mean_Confidence.svg")

In [70]:
df_QWEN = df_Results[df_Results['Model']=='QWEN 2.5']
df_QWEN

,Prompt_ID,Content_Type,Model,temperature,top_p,top_k,runtime,BLEU,Precision,Recall,F1 Score,NEUTRAL,ENTAILMENT,CONTRADICTION,Consistency Label
0,1,NOC,QWEN 2.5,0.2,0.5,20,7.041744,0.460551,0.600000,0.367347,0.455696,0.926761,0.070157,0.003082,Neutral
1,1,NOC,QWEN 2.5,0.2,0.5,40,1.287806,0.460551,0.610169,0.367347,0.458599,0.896464,0.100589,0.002947,Neutral
2,1,NOC,QWEN 2.5,0.2,0.5,90,1.351361,0.460551,0.603175,0.387755,0.472050,0.910539,0.086862,0.002600,Neutral
3,1,NOC,QWEN 2.5,0.2,0.7,20,1.286819,0.460551,0.600000,0.367347,0.455696,0.926761,0.070157,0.003082,Neutral
4,1,NOC,QWEN 2.5,0.2,0.7,40,1.324588,0.460551,0.610169,0.367347,0.458599,0.885681,0.111349,0.002970,Neutral
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3154,30,Graduate Survey,QWEN 2.5,0.9,0.7,40,1.604347,0.551325,0.652174,0.810811,0.722892,0.996563,0.002961,0.000475,Neutral
3155,30,Graduate Survey,QWEN 2.5,0.9,0.7,90,1.715946,0.505409,0.560000,0.756757,0.643678,0.996371,0.003171,0.000458,Neutral
3156,30,Graduate Survey,QWEN 2.5,0.9,0.9,20,1.655282,0.551325,0.600000,0.810811,0.689655,0.996473,0.003060,0.000467,Neutral
3157,30,Graduate Survey,QWEN 2.5,0.9,0.9,40,1.786372,0.505409,0.500000,0.756757,0.602151,0.996725,0.002784,0.000491,Neutral
3158,30,Graduate Survey,QWEN 2.5,0.9,0.9,90,1.690030,0.551325,0.604167,0.783784,0.682353,0.996162,0.003390,0.000447,Neutral

In [71]:
df_QWEN_Precision_Dit = df_QWEN.groupby(['temperature','top_p','top_k'])['Precision'].describe().round(3).reset_index()
df_QWEN_Precision_Dit

,temperature,top_p,top_k,count,mean,std,min,25%,50%,75%,max
0,0.2,0.5,20,30.0,0.503,0.218,0.158,0.355,0.458,0.584,1.0
1,0.2,0.5,40,30.0,0.505,0.214,0.158,0.386,0.473,0.584,1.0
2,0.2,0.5,90,30.0,0.499,0.217,0.158,0.367,0.458,0.584,1.0
3,0.2,0.7,20,30.0,0.507,0.219,0.158,0.369,0.476,0.587,1.0
4,0.2,0.7,40,30.0,0.501,0.222,0.158,0.345,0.473,0.600,1.0
5,0.2,0.7,90,30.0,0.494,0.222,0.158,0.344,0.467,0.593,1.0
6,0.2,0.9,20,30.0,0.507,0.220,0.158,0.347,0.473,0.606,1.0
7,0.2,0.9,40,30.0,0.503,0.218,0.158,0.344,0.462,0.594,1.0
8,0.2,0.9,90,30.0,0.498,0.219,0.158,0.332,0.460,0.594,1.0
9,0.5,0.5,20,30.0,0.495,0.219,0.158,0.345,0.479,0.527,1.0
10,0.5,0.5,40,30.0,0.508,0.219,0.158,0.342,0.489,0.584,1.0
11,0.5,0.5,90,30.0,0.506,0.215,0.158,0.355,0.478,0.584,1.0
12,0.5,0.7,20,30.0,0.511,0.214,0.176,0.368,0.484,0.586,1.0
13,0.5,0.7,40,30.0,0.502,0.220,0.158,0.339,0.462,0.622,1.0
14,0.5,0.7,90,30.0,0.504,0.230,0.158,0.349,0.443,0.641,1.0
15,0.5,0.9,20,30.0,0.503,0.224,0.158,0.329,0.462,0.617,1.0
16,0.5,0.9,40,30.0,0.491,0.223,0.158,0.353,0.443,0.572,1.0
17,0.5,0.9,90,30.0,0.503,0.226,0.195,0.343,0.454,0.637,1.0
18,0.9,0.5,20,30.0,0.501,0.213,0.158,0.367,0.465,0.579,1.0
19,0.9,0.5,40,30.0,0.505,0.215,0.158,0.368,0.466,0.582,1.0
20,0.9,0.5,90,30.0,0.494,0.214,0.158,0.363,0.462,0.540,1.0
21,0.9,0.7,20,30.0,0.478,0.226,0.164,0.318,0.465,0.549,1.0
22,0.9,0.7,40,30.0,0.513,0.223,0.167,0.371,0.459,0.638,1.0
23,0.9,0.7,90,30.0,0.501,0.220,0.158,0.360,0.456,0.597,1.0
24,0.9,0.9,20,30.0,0.479,0.207,0.158,0.327,0.449,0.566,1.0
25,0.9,0.9,40,30.0,0.492,0.230,0.158,0.342,0.413,0.610,1.0
26,0.9,0.9,90,30.0,0.495,0.220,0.158,0.359,0.447,0.578,1.0

In [76]:
df_QWEN_Precision_Dit.to_csv('Tables/QWEN_Precision_Stats.csv',index=False)

In [72]:
df_QWEN_Recall_Dit = df_QWEN.groupby(['temperature','top_p','top_k'])['Recall'].describe().round(3).reset_index()
df_QWEN_Recall_Dit

,temperature,top_p,top_k,count,mean,std,min,25%,50%,75%,max
0,0.2,0.5,20,30.0,0.544,0.205,0.282,0.369,0.497,0.700,0.959
1,0.2,0.5,40,30.0,0.554,0.203,0.282,0.369,0.519,0.705,0.959
2,0.2,0.5,90,30.0,0.551,0.198,0.282,0.377,0.486,0.700,0.959
3,0.2,0.7,20,30.0,0.552,0.209,0.237,0.372,0.519,0.705,0.959
4,0.2,0.7,40,30.0,0.549,0.202,0.237,0.392,0.486,0.705,0.959
5,0.2,0.7,90,30.0,0.549,0.207,0.237,0.373,0.497,0.705,0.959
6,0.2,0.9,20,30.0,0.552,0.200,0.282,0.378,0.486,0.705,0.959
7,0.2,0.9,40,30.0,0.545,0.199,0.271,0.382,0.486,0.700,0.959
8,0.2,0.9,90,30.0,0.548,0.194,0.282,0.383,0.486,0.681,0.959
9,0.5,0.5,20,30.0,0.548,0.199,0.282,0.380,0.503,0.703,0.959
10,0.5,0.5,40,30.0,0.550,0.206,0.282,0.374,0.481,0.705,0.959
11,0.5,0.5,90,30.0,0.553,0.202,0.282,0.369,0.492,0.700,0.959
12,0.5,0.7,20,30.0,0.551,0.199,0.282,0.381,0.519,0.727,0.959
13,0.5,0.7,40,30.0,0.552,0.197,0.282,0.391,0.479,0.726,0.959
14,0.5,0.7,90,30.0,0.518,0.201,0.237,0.339,0.471,0.657,0.959
15,0.5,0.9,20,30.0,0.538,0.201,0.282,0.373,0.486,0.698,0.959
16,0.5,0.9,40,30.0,0.539,0.202,0.237,0.388,0.530,0.676,0.959
17,0.5,0.9,90,30.0,0.528,0.207,0.260,0.361,0.446,0.724,0.959
18,0.9,0.5,20,30.0,0.553,0.199,0.282,0.392,0.504,0.696,0.959
19,0.9,0.5,40,30.0,0.558,0.197,0.282,0.389,0.532,0.700,0.959
20,0.9,0.5,90,30.0,0.545,0.202,0.282,0.350,0.497,0.696,0.959
21,0.9,0.7,20,30.0,0.524,0.202,0.237,0.379,0.443,0.702,0.959
22,0.9,0.7,40,30.0,0.542,0.201,0.237,0.366,0.483,0.724,0.959
23,0.9,0.7,90,30.0,0.541,0.198,0.237,0.367,0.502,0.673,0.959
24,0.9,0.9,20,30.0,0.529,0.208,0.237,0.351,0.475,0.704,0.959
25,0.9,0.9,40,30.0,0.538,0.199,0.237,0.387,0.460,0.696,0.959
26,0.9,0.9,90,30.0,0.536,0.204,0.263,0.387,0.459,0.736,0.959

In [77]:
df_QWEN_Recall_Dit.to_csv('Tables/QWEN_Recall_Stats.csv',index=False)

In [84]:
df_QWEN_F1Score_Dit = df_QWEN.groupby(['temperature','top_p','top_k'])['F1 Score'].describe().round(5).reset_index()
df_QWEN_F1Score_Dit

,temperature,top_p,top_k,count,mean,std,min,25%,50%,75%,max
0,0.2,0.5,20,30.0,0.50689,0.19234,0.21429,0.37088,0.45078,0.62431,0.94949
1,0.2,0.5,40,30.0,0.51315,0.18954,0.21429,0.37524,0.48402,0.61667,0.94949
2,0.2,0.5,90,30.0,0.50885,0.18978,0.21429,0.36419,0.47169,0.61392,0.94949
3,0.2,0.7,20,30.0,0.51409,0.19628,0.19565,0.36322,0.47527,0.62431,0.94949
4,0.2,0.7,40,30.0,0.50895,0.19473,0.19565,0.37608,0.45298,0.61667,0.94949
5,0.2,0.7,90,30.0,0.50379,0.19494,0.19565,0.36510,0.44045,0.61667,0.94949
6,0.2,0.9,20,30.0,0.51540,0.19420,0.21429,0.37273,0.46758,0.62044,0.94949
7,0.2,0.9,40,30.0,0.50692,0.18986,0.21429,0.36820,0.45715,0.61930,0.94949
8,0.2,0.9,90,30.0,0.50698,0.18989,0.21429,0.36496,0.45244,0.61392,0.94949
9,0.5,0.5,20,30.0,0.50368,0.18856,0.21429,0.35846,0.48280,0.59607,0.94949
10,0.5,0.5,40,30.0,0.51284,0.19367,0.21429,0.37043,0.48130,0.62500,0.94949
11,0.5,0.5,90,30.0,0.51383,0.19039,0.21429,0.36927,0.47789,0.62500,0.94949
12,0.5,0.7,20,30.0,0.51644,0.18902,0.23077,0.38121,0.47134,0.62234,0.94949
13,0.5,0.7,40,30.0,0.51130,0.19017,0.21429,0.36187,0.49051,0.59829,0.94949
14,0.5,0.7,90,30.0,0.49482,0.19790,0.19355,0.35066,0.44055,0.59706,0.94949
15,0.5,0.9,20,30.0,0.50378,0.19321,0.21429,0.35774,0.45347,0.58618,0.94949
16,0.5,0.9,40,30.0,0.49830,0.19353,0.19565,0.36606,0.48672,0.59931,0.94949
17,0.5,0.9,90,30.0,0.49917,0.19552,0.25882,0.35412,0.43748,0.59706,0.94949
18,0.9,0.5,20,30.0,0.51067,0.18714,0.21429,0.36942,0.47677,0.58182,0.94949
19,0.9,0.5,40,30.0,0.51349,0.18577,0.21429,0.38451,0.47497,0.58764,0.94949
20,0.9,0.5,90,30.0,0.50384,0.18907,0.21429,0.35281,0.48883,0.58336,0.94949
21,0.9,0.7,20,30.0,0.48459,0.19579,0.19355,0.34466,0.42021,0.58404,0.94949
22,0.9,0.7,40,30.0,0.51016,0.18952,0.19565,0.39480,0.44251,0.59706,0.94949
23,0.9,0.7,90,30.0,0.50565,0.19199,0.19565,0.35541,0.47716,0.59737,0.94949
24,0.9,0.9,20,30.0,0.48658,0.18116,0.21429,0.35365,0.45998,0.60188,0.94949
25,0.9,0.9,40,30.0,0.49856,0.19754,0.20690,0.34962,0.48867,0.59447,0.94949
26,0.9,0.9,90,30.0,0.50082,0.19585,0.21277,0.35723,0.46354,0.62360,0.94949

In [78]:
df_QWEN_F1Score_Dit.to_csv('Tables/QWEN_F1Score_Stats.csv',index=False)

In [74]:
df_QWEN_Entailments = df_QWEN[df_QWEN['Consistency Label']=='Entailment']
df_QWEN_Entailments

,Prompt_ID,Content_Type,Model,temperature,top_p,top_k,runtime,BLEU,Precision,Recall,F1 Score,NEUTRAL,ENTAILMENT,CONTRADICTION,Consistency Label
6,1,NOC,QWEN 2.5,0.2,0.9,20,1.421864,0.460551,0.565217,0.397959,0.467066,0.480265,0.517067,0.002667,Entailment
108,2,NOC,QWEN 2.5,0.2,0.5,20,7.387105,0.205554,0.529412,0.494505,0.511364,0.093928,0.905006,0.001067,Entailment
109,2,NOC,QWEN 2.5,0.2,0.5,40,1.845334,0.205554,0.521277,0.538462,0.529730,0.068590,0.930409,0.001001,Entailment
110,2,NOC,QWEN 2.5,0.2,0.5,90,1.671859,0.205554,0.512195,0.461538,0.485549,0.047024,0.952105,0.000870,Entailment
111,2,NOC,QWEN 2.5,0.2,0.7,20,1.739404,0.303981,0.583333,0.538462,0.560000,0.069375,0.929624,0.001001,Entailment
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2722,26,Graduate Survey,QWEN 2.5,0.9,0.7,40,1.560835,0.824237,0.508772,0.763158,0.610526,0.016891,0.982389,0.000720,Entailment
2723,26,Graduate Survey,QWEN 2.5,0.9,0.7,90,1.539074,0.824237,0.491228,0.736842,0.589474,0.079588,0.919727,0.000685,Entailment
2724,26,Graduate Survey,QWEN 2.5,0.9,0.9,20,1.589002,0.824237,0.442623,0.710526,0.545455,0.074094,0.923075,0.002831,Entailment
2725,26,Graduate Survey,QWEN 2.5,0.9,0.9,40,1.278300,0.824237,0.673913,0.815789,0.738095,0.008112,0.991002,0.000886,Entailment
2726,26,Graduate Survey,QWEN 2.5,0.9,0.9,90,1.403333,0.824237,0.549020,0.736842,0.629213,0.008762,0.990313,0.000925,Entailment

In [75]:
df_QWEN_Entailments_Count = df_QWEN_Entailments.groupby(['temperature','top_p','top_k'])['ENTAILMENT'].describe().round(3).reset_index()
df_QWEN_Entailments_Count

,temperature,top_p,top_k,count,mean,std,min,25%,50%,75%,max
0,0.2,0.5,20,18.0,0.876,0.135,0.601,0.749,0.952,0.978,0.992
1,0.2,0.5,40,21.0,0.871,0.133,0.561,0.750,0.930,0.973,0.991
2,0.2,0.5,90,20.0,0.896,0.104,0.708,0.807,0.947,0.976,0.992
3,0.2,0.7,20,19.0,0.868,0.140,0.616,0.743,0.942,0.978,0.992
4,0.2,0.7,40,20.0,0.896,0.108,0.699,0.795,0.946,0.979,0.992
5,0.2,0.7,90,21.0,0.904,0.093,0.708,0.833,0.942,0.975,0.992
6,0.2,0.9,20,21.0,0.863,0.153,0.517,0.766,0.942,0.974,0.992
7,0.2,0.9,40,19.0,0.874,0.143,0.596,0.791,0.942,0.976,0.993
8,0.2,0.9,90,20.0,0.850,0.154,0.551,0.755,0.927,0.972,0.991
9,0.5,0.5,20,20.0,0.894,0.112,0.663,0.810,0.965,0.976,0.992
10,0.5,0.5,40,19.0,0.892,0.125,0.594,0.848,0.965,0.973,0.991
11,0.5,0.5,90,20.0,0.893,0.101,0.708,0.814,0.926,0.975,0.991
12,0.5,0.7,20,19.0,0.899,0.127,0.485,0.901,0.942,0.984,0.991
13,0.5,0.7,40,19.0,0.898,0.107,0.646,0.826,0.951,0.976,0.991
14,0.5,0.7,90,17.0,0.884,0.159,0.429,0.832,0.972,0.982,0.992
15,0.5,0.9,20,20.0,0.918,0.085,0.708,0.902,0.948,0.975,0.991
16,0.5,0.9,40,19.0,0.867,0.175,0.351,0.808,0.942,0.984,0.993
17,0.5,0.9,90,20.0,0.894,0.116,0.671,0.770,0.949,0.986,0.993
18,0.9,0.5,20,21.0,0.893,0.105,0.629,0.860,0.922,0.973,0.991
19,0.9,0.5,40,19.0,0.866,0.159,0.514,0.783,0.947,0.974,0.991
20,0.9,0.5,90,20.0,0.883,0.135,0.602,0.819,0.961,0.975,0.992
21,0.9,0.7,20,18.0,0.880,0.128,0.632,0.795,0.939,0.972,0.992
22,0.9,0.7,40,19.0,0.901,0.110,0.663,0.832,0.949,0.982,0.992
23,0.9,0.7,90,17.0,0.892,0.106,0.654,0.862,0.920,0.973,0.991
24,0.9,0.9,20,19.0,0.874,0.151,0.568,0.744,0.970,0.982,0.991
25,0.9,0.9,40,17.0,0.885,0.159,0.453,0.898,0.968,0.983,0.993
26,0.9,0.9,90,18.0,0.887,0.137,0.521,0.807,0.958,0.985,0.993