In [1]:
import pandas as pd 
import json

In [2]:
from pathlib import Path

In [3]:
with open('Compentencies_Features.json', 'r') as f:
    Feature_List = json.load(f)

In [4]:
Feature_List

['Numeracy',
 'Social Perceptiveness',
 'Negotiating',
 'Digital Literacy',
 'Persuading',
 'Evaluation',
 'Writing',
 'Instructing',
 'Active Listening',
 'Oral Expression',
 'Reading Comprehension']

In [5]:

df_Data = pd.read_csv('Tbl_NOC_Competencies.csv')

In [6]:
df_Data

,OaSIS 2021 Codes,OaSIS 2021 Labels,Active Listening,Digital Literacy,Numeracy,Oral Comprehension,Oral Expression,Reading Comprehension,Writing,Decision Making,...,Management of Financial Resources,Management of Material Resources,Management of Personnel Resources,Monitoring,Time Management,Coordinating,Instructing,Negotiating,Persuading,Social Perceptiveness
0,"00010,00",Legislators,4,3,3,5,5,4,4,5,...,5,5,5,5,5,5,3,5,5,5
1,"00011,00",Senior government managers and officials,4,4,4,5,5,5,5,5,...,5,5,5,5,5,5,4,5,5,4
2,"00012,00","Senior managers - financial, communications an...",4,4,4,5,5,5,5,5,...,5,5,5,5,5,5,4,5,5,4
3,"00013,00","Senior managers - health, education, social an...",4,4,4,5,5,5,5,5,...,5,5,5,5,5,5,4,5,5,5
4,"00014,00","Senior managers - trade, broadcasting and othe...",4,4,4,5,5,5,5,5,...,5,5,5,5,5,5,4,5,5,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
895,"95105,03",Fur cutters,1,0,1,1,1,1,1,1,...,0,2,0,1,1,0,1,0,0,0
896,"95105,04",Leather cutters,1,0,1,1,1,1,1,1,...,0,2,0,1,1,0,1,0,0,0
897,"95106,00",Labourers in food and beverage processing,1,0,1,1,1,1,1,1,...,0,2,0,1,1,1,0,0,0,0
898,"95107,00",Labourers in fish and seafood processing,1,0,1,1,1,1,1,1,...,0,2,0,1,1,1,0,0,0,0
899,"95109,00","Other labourers in processing, manufacturing a...",1,0,1,1,1,1,1,1,...,0,1,0,1,1,1,0,0,0,0

In [7]:
Target = ['OaSIS 2021 Labels']
All_Columns = Feature_List + Target
df_Data_Reduced = df_Data[All_Columns]

In [8]:
df_Data_Reduced = df_Data_Reduced.rename(columns={'OaSIS 2021 Labels':'Target'})
print(df_Data_Reduced)

     Numeracy  Social Perceptiveness  Negotiating  Digital Literacy  \
0           3                      5            5                 3
1           4                      4            5                 4
2           4                      4            5                 4
3           4                      5            5                 4
4           4                      4            5                 4
..        ...                    ...          ...               ...
895         1                      0            0                 0
896         1                      0            0                 0
897         1                      0            0                 0
898         1                      0            0                 0
899         1                      0            0                 0

     Persuading  Evaluation  Writing  Instructing  Active Listening  \
0             5           4        4            3                 4
1             5           5        5            4                 4
2             5           5        5            4                 4
3             5           5        5            4                 4
4             5           5        5            4                 4
..          ...         ...      ...          ...               ...
895           0           1        1            1                 1
896           0           1        1            1                 1
897           0           1        1            0                 1
898           0           1        1            0                 1
899           0           1        1            0                 1

     Oral Expression  Reading Comprehension  \
0                  5                      4
1                  5                      5
2                  5                      5
3                  5                      5
4                  5                      5
..               ...                    ...
895                1                      1
896                1                      1
897                1                      1
898                1                      1
899                1                      1

                                                Target
0                                          Legislators
1             Senior government managers and officials
2    Senior managers - financial, communications an...
3    Senior managers - health, education, social an...
4    Senior managers - trade, broadcasting and othe...
..                                                 ...
895                                        Fur cutters
896                                    Leather cutters
897          Labourers in food and beverage processing
898           Labourers in fish and seafood processing
899  Other labourers in processing, manufacturing a...

[900 rows x 12 columns]

Generating Simple Nearest Neighbour Model

In [9]:
from sklearn.neighbors import NearestNeighbors
from sklearn.preprocessing import StandardScaler

In [10]:
competencies = df_Data_Reduced.drop(columns=["Target"])
jobs = df_Data_Reduced["Target"]

In [11]:
scaler = StandardScaler()
competencies_scaled = scaler.fit_transform(competencies)

In [12]:
nn = NearestNeighbors(
    n_neighbors=7,
    metric='euclidean'   
)

nn.fit(competencies_scaled)

NearestNeighbors(metric='euclidean', n_neighbors=7)

In [13]:
def recommend_jobs(user_input):

    user_scaled = scaler.transform([user_input])

    distances, indices = nn.kneighbors(user_scaled)

    results = jobs.iloc[indices[0]].reset_index(drop=True)
    distances = distances[0]

    output = results.to_frame(name="NOC Occupation")
    output["Distance"] = distances

    return output

In [14]:
'''
"Data scientists": {
        "Numeracy": 5,
        "Social Perceptiveness": 2,
        "Negotiating": 2,
        "Digital Literacy": 5,
        "Persuading": 3,
        "Evaluation": 5,
        "Writing": 4,
        "Instructing": 4,
        "Active Listening": 4,
        "Oral Expression": 4,
        "Reading Comprehension": 4
    },

    "Ship and train service attendants": {
        "Numeracy": 1,
        "Social Perceptiveness": 3,
        "Negotiating": 2,
        "Digital Literacy": 0,
        "Persuading": 2,
        "Evaluation": 1,
        "Writing": 1,
        "Instructing": 0,
        "Active Listening": 2,
        "Oral Expression": 2,
        "Reading Comprehension": 1
    }
'''

'\n"Data scientists": {\n        "Numeracy": 5,\n        "Social Perceptiveness": 2,\n        "Negotiating": 2,\n        "Digital Literacy": 5,\n        "Persuading": 3,\n        "Evaluation": 5,\n        "Writing": 4,\n        "Instructing": 4,\n        "Active Listening": 4,\n        "Oral Expression": 4,\n        "Reading Comprehension": 4\n    },\n\n    "Ship and train service attendants": {\n        "Numeracy": 1,\n        "Social Perceptiveness": 3,\n        "Negotiating": 2,\n        "Digital Literacy": 0,\n        "Persuading": 2,\n        "Evaluation": 1,\n        "Writing": 1,\n        "Instructing": 0,\n        "Active Listening": 2,\n        "Oral Expression": 2,\n        "Reading Comprehension": 1\n    }\n'

In [15]:
user = [1,3,2,0,2,1,1,0,2,2,1]

recommended_jobs = recommend_jobs(user)

c:\ProgramData\anaconda3\envs\myConda\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

In [16]:
recommended_jobs

                                   NOC Occupation  Distance
0               Ship and train service attendants  0.000000
1  Other support occupations in personal services  0.854937
2    Guest service attendants and baggage porters  1.127118
3                      Taxi and limousine drivers  1.138589
4                      Manicurists and pedicurist  1.152873
5                                  Tattoo artists  1.152873
6   Attendants in amusement, recreation and sport  1.167277

In [60]:
ds_Sample = recommended_jobs.merge(df_Data_Reduced.rename(columns={'Target':'NOC Occupation'}), on=['NOC Occupation'])

In [61]:
ds_Sample

,NOC Occupation,Distance,Numeracy,Social Perceptiveness,Negotiating,Digital Literacy,Persuading,Evaluation,Writing,Instructing,Active Listening,Oral Expression,Reading Comprehension
0,Ship and train service attendants,1.110223e-16,1,3,2,0,2,1,1,0,2,2,1
1,Other support occupations in personal services,2.822205e-02,1,3,3,0,2,1,1,0,2,2,1
2,Guest service attendants and baggage porters,3.391827e-02,1,3,2,0,1,0,1,0,2,2,1
3,Manicurists and pedicurist,4.549957e-02,1,3,2,0,2,2,1,1,2,2,1
4,Tattoo artists,4.549957e-02,1,3,2,0,2,2,1,1,2,2,1
5,Taxi and limousine drivers,4.914159e-02,1,3,2,1,2,2,1,0,2,2,1
6,"Attendants in amusement, recreation and sport",5.181264e-02,1,2,1,0,2,1,1,0,2,2,1

In [62]:
ds_Sample.to_csv('STSA_Cosine_Return_Sample.csv',index=False)

Saving the Model

In [18]:
import joblib

In [19]:
joblib.dump({
    "model": nn,
    "scaler": scaler,
    "jobs": jobs,
    "X_scaled": competencies_scaled
}, "career_matcher.pkl")

['career_matcher.pkl']

In [20]:
jobs.to_csv('jobs.csv')